language: java
jdk:
- oraclejdk8
services: mongodb
cache:
  directories:
  - "$HOME/.m2"
addons:
  ssh_known_hosts: vps394659.ovh.net
before_deploy:
- openssl aes-256-cbc -K $encrypted_08f8a0b6216a_key -iv $encrypted_08f8a0b6216a_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  script: sh deploy.sh
  skip_cleanup: true
  on:
    branch: master